Traceback (most recent call last):
  File "/home/philipdb/dat2/datsyn_project/pytorch-lightning-template/trainer.py", line 85, in <module>
    trainer = pl.Trainer(
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: Trainer.__init__() got an unexpected keyword argument 'prepare_data_per_node'
Traceback (most recent call last):
  File "/home/philipdb/dat2/datsyn_project/pytorch-lightning-template/trainer.py", line 85, in <module>
    trainer = pl.Trainer(
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: Trainer.__init__() got an unexpected keyword argument 'prepare_data_per_node'