Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/home/philipdb/dat2/datsyn_project/pytorch-lightning-template/trainer.py", line 103, in <module>
    trainer.fit(model, datamodule=dm)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 932, in _run
    self._data_connector.prepare_data()
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 92, in prepare_data
    dm_prepare_data_per_node = datamodule.prepare_data_per_node
AttributeError: 'RBKDataModule' object has no attribute 'prepare_data_per_node'
Traceback (most recent call last):
  File "/home/philipdb/dat2/datsyn_project/pytorch-lightning-template/trainer.py", line 103, in <module>
    trainer.fit(model, datamodule=dm)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 932, in _run
    self._data_connector.prepare_data()
  File "/home/philipdb/anaconda3/envs/tdt4265/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 92, in prepare_data
    dm_prepare_data_per_node = datamodule.prepare_data_per_node
AttributeError: 'RBKDataModule' object has no attribute 'prepare_data_per_node'